version: "3.3"

services:

  kibana:
    image: kibana:7.3.2
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200

  elasticsearch:
    image: elasticsearch:7.3.2
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node

  logstash:
    image: logstash:7.3.2
    container_name: logstash
    ports:
      - "5044:5044"
      - "9600:9600" 
      - "2203:22"
    volumes:
      - ./logstash/command-input.conf:/usr/share/logstash/pipeline/command-input.conf
      - ./logstash/jdbc-input.conf:/usr/share/logstash/pipeline/jdbc-input.conf
      - ./logstash/filebeat-input.conf:/usr/share/logstash/pipeline/filebeat-input.conf
      - ./logstash/output.conf:/usr/share/logstash/pipeline/output.conf
      - ./logstash/command-filter.conf:/usr/share/logstash/pipeline/command-filter.conf
      - ./logstash/retrieve-data.sh:/usr/bin/retrieve-data.sh
      - ./logstash/query-locks.sql:/etc/logstash/queries/query-locks.sql
      - ./logstash/postgresql-42.1.4.jar:/usr/share/logstash/logstash-core/lib/jars/postgresql-42-1-4.jar
    depends_on:
      - elasticsearch

  postgresql:
    image: postgres:11
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "main"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

  transfer_app:
    build: ./transferapp
    container_name: transferapp
    volumes:
      - ./filebeat/filebeat.yml:/etc/filebeat/filebeat.yml
      - ./filebeat/inputs.yml:/etc/filebeat/inputs.yml